{% set name = "circlify" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/elmotec/circlify/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d168822e6e2690a09d79a7a5485e916bb144f003c0e75e809a411f1c81f8366e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - circlify
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/elmotec/circlify
  summary: Circle packing algorithm for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
