{% set name = "circlify" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/elmotec/circlify/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 558381b1ec1a6cba5d49067c1ad9c8da6026928403445fe83b003eed56a0ba64

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - circlify
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/elmotec/circlify
  summary: Circle packing algorithm for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
